name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./backend

      - name: Push Backend Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend:latest


      - name: Deploy
        run: |
          docker stop backend || true
          docker rm backend || true
          docker stop frontend || true
          docker rm frontend || true

          docker pull ghcr.io/${{ github.repository_owner }}/backend:latest
          cd /Desktop/project2/Expense_Tracker 1/Expense_Tracker
          docker compose down 
          docker compose up -d
       
